package it.vupo.beerduino.recipe;


/**
 * Classe per la conferma della ricetta (viene visualizzato un pannello grafico in cui si riassume 
 * il contenuto della ricetta)
 *
 * @author Alessandro Morniroli
 */
public class Confirm extends DataAndFunction {

    /**
     * Costruttore di default
     * @param parent jframe parent
     * @param modal true per farlo rimanere in primo piano, false altrimenti
     */
    public Confirm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * Costruttore secondario
     *
     * @param parent jframe parent
     * @param modal true per farlo rimanere in primo piano, false altrimenti
     * @param recipe ricetta da confermare
     */
    public Confirm(java.awt.Frame parent, boolean modal, Recipe recipe) {
        super(parent, modal);
        super.setRecipe(recipe);
        initComponents();
        this.check();
    }

    /**
     * Creazione di una JTextArea in cui viene scritto il riassunto della ricetta
     * (vari step di mash e di boil, oltre al tempo di bollitura totale)
     */
    public void check() {
        String tmp;
        this.textArea.append("MASH STEP\n\n");
        for (int i = 0; i < super.getRecipe().getMash().size(); i++) {
            tmp = new String();
            tmp += "Name " + super.getRecipe().getMash().get(i).getNome() + " ";
            tmp += super.getRecipe().getMash().get(i).getLength() + " minutes";
            tmp += super.getRecipe().getMash().get(i).getEndTemp() + " °C" + "\n";
            this.textArea.append(tmp);
        }

        this.textArea.append("\n");
        this.textArea.append("HOP STEP\n\n");
        for (int i = 0; i < super.getRecipe().getHops().size(); i++) {
            tmp = new String();
            tmp += "Name " + super.getRecipe().getHops().get(i).getName() + " ";
            tmp += super.getRecipe().getHops().get(i).getMinutes() + " minutes" + "\n";
            this.textArea.append(tmp);
        }
        this.textArea.append("\n");
        this.textArea.append("BOIL TIME\n\n");
        this.textArea.append("Minutes" + Integer.toString(super.getRecipe().getBollitura()) + "\n");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        confirmPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Check"));

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout confirmPanelLayout = new org.jdesktop.layout.GroupLayout(confirmPanel);
        confirmPanel.setLayout(confirmPanelLayout);
        confirmPanelLayout.setHorizontalGroup(
            confirmPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, confirmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(confirmPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .add(confirmPanelLayout.createSequentialGroup()
                        .add(cancelButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(okButton)))
                .addContainerGap())
        );
        confirmPanelLayout.setVerticalGroup(
            confirmPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, confirmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(confirmPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(okButton)
                    .add(cancelButton))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(confirmPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(confirmPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Azione relativa al pulsante ok
     *
     * @param evt evento del mouse (click)
     */
    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
        super.getRecipe().setCheck(true);
        this.dispose();
}//GEN-LAST:event_okButtonActionPerformed

    /**
     * Azione relativa al pulsante cancel
     *
     * @param evt evento del mouse (click)
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        super.getRecipe().setCheck(false);
        this.dispose();
}//GEN-LAST:event_cancelButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel confirmPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okButton;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
